//! Phase-0 wire-format gate: 5 `RapidRequest` byte strings captured from
//! Java's `RapidRequest.toByteArray()` are decoded by prost and re-encoded
//! to *the same bytes*. Mismatch here means our proto bindings have drifted
//! from upstream and interop is broken.
//!
//! Vectors live at `vectors/wire_v0.txt`, generated by
//! `tools/dump-vectors/WireDump.java`.

use std::collections::BTreeMap;

use prost::Message;
use rapid::pb;

const VECTORS: &str = include_str!("../vectors/wire_v0.txt");

fn hex_decode(s: &str) -> Vec<u8> {
    let s = s.trim();
    assert!(s.len().is_multiple_of(2), "odd-length hex");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("valid hex byte"))
        .collect()
}

fn load_vectors() -> BTreeMap<String, Vec<u8>> {
    let mut out = BTreeMap::new();
    for line in VECTORS.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (name, hex) = line.split_once('=').expect("name=hex");
        out.insert(name.to_string(), hex_decode(hex));
    }
    assert!(
        out.len() >= 5,
        "expected at least 5 vectors, got {}",
        out.len()
    );
    out
}

#[test]
fn java_vectors_round_trip_byte_for_byte() {
    let vectors = load_vectors();
    for (name, bytes) in &vectors {
        let decoded = pb::RapidRequest::decode(bytes.as_slice())
            .unwrap_or_else(|e| panic!("decode failed for {name}: {e}"));
        let mut re_encoded = Vec::with_capacity(bytes.len());
        decoded
            .encode(&mut re_encoded)
            .unwrap_or_else(|e| panic!("encode failed for {name}: {e}"));
        assert_eq!(
            re_encoded, *bytes,
            "{name}: byte-for-byte roundtrip failure"
        );
    }
}

#[test]
fn vector_oneof_variants_match_expected() {
    let vectors = load_vectors();
    let pre_join = pb::RapidRequest::decode(vectors["preJoin"].as_slice()).unwrap();
    assert!(matches!(
        pre_join.content,
        Some(pb::rapid_request::Content::PreJoinMessage(_))
    ));
    let join = pb::RapidRequest::decode(vectors["join"].as_slice()).unwrap();
    assert!(matches!(
        join.content,
        Some(pb::rapid_request::Content::JoinMessage(_))
    ));
    let batched = pb::RapidRequest::decode(vectors["batchedAlert"].as_slice()).unwrap();
    assert!(matches!(
        batched.content,
        Some(pb::rapid_request::Content::BatchedAlertMessage(_))
    ));
    let probe = pb::RapidRequest::decode(vectors["probe"].as_slice()).unwrap();
    assert!(matches!(
        probe.content,
        Some(pb::rapid_request::Content::ProbeMessage(_))
    ));
    let leave = pb::RapidRequest::decode(vectors["leave"].as_slice()).unwrap();
    assert!(matches!(
        leave.content,
        Some(pb::rapid_request::Content::LeaveMessage(_))
    ));
}
